services:
  web:
    build: ./docker/php
    container_name: app
    volumes:
      - './php:/var/www/html'
    ports:
      - "8080:80"
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    build: ./docker/mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: cuisine
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    depends_on:
      - db
    volumes:
      - './theme/blueberry:/var/www/html/themes/blueberry'