version: '3'

services:
  web:
    image: php:7.2-apache
    container_name: app
    volumes:
      - ./php:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    image: mysql:5.7
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cuisine
      MYSQL_USER: admin
      MYSQL_PASSWORD: raspbian
    ports:
      - "9906:3306"
    volumes:
      - ./mysql:/var/lib/mysql